name: Continuous Integration
on:
  push:
    branches:
      - master
      - 'MTC\-[0-9]+'
  pull_request:

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]
        mautic-version: ['5.0', '6.0', '7.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install composer requirements.
        run: composer require mautic/core-lib:^${{ matrix.mautic-version }} --dev --no-update && composer install
      - name: Check PHP CS
        run: ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --dry-run --using-cache no --show-progress dots -v
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --no-progress
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
